import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from "./(common)/Header"
import Footer from "./(common)/Footer"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "nextjs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
        <html lang="en">
            <body className={`antialiased`}>
                <Header/>
                <main>{children}</main>
                <Footer style={{color: "red"}} />
            </body>
		</html>
	);
}
